name: HTML Validation Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout código
        uses: actions/checkout@v2

      # Paso 2: Instalación de aspell (diccionario español)
      - name: Install aspell (Spanish dictionary)
        run: sudo apt-get install aspell aspell-es

      # Paso 3: Validación ortográfica en español
      - name: Verificar ortografía en español
        run: |
          find . -name "*.html" -type f -exec sh -c 'cat {} | aspell --lang=es list | grep -v "[A-Za-z]"' \;

      # Paso 4: Instalación de html-validate
      - name: Install html-validate
        run: npm install html-validate

      # Paso 5: Validación general de HTML
      - name: Validar HTML
        run: npx html-validate "**/*.html" --config .htmlvalidate.json

