name: Spell Check Pipeline

on:
  push:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Install aspell (Spanish dictionary)
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-es

      - name: Verificar ortografía en index.html
        run: |
          # Filtrar palabras reservadas de HTML y CSS antes de la verificación ortográfica
          sed -e 's/<[^>]*>//g' -e 's/{[^}]*}//g' index.html |   # Eliminar etiquetas HTML y propiedades CSS
          grep -n -E -o '\b(Lorem|ipsum|sit|amet|consectetur|adipiscing|elit|Ut|enim|ad|minim|veniam|quis|nostrud|exercitation)\b' |  # Buscar palabras comunes y obtener número de línea
          aspell --lang=es list || true          # Verificar ortografía con aspell


