name: Spell Check Pipeline

on:
  push:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Install aspell (Spanish dictionary)
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-es

      - name: Verificar ortografía en index.html
        run: |
          # Encuentra el archivo index.html y verifica la ortografía
          aspell --lang=es list < index.html || true  # Usa '|| true' para evitar que el comando falle si hay errores



